/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import org.eclipse.persistence.sessions.server.ConnectionPool;
import settings.Conexion;
import settings.Pelicula;

/**
 *
 * @author PC-HOGAR
 */
public class CargarPelicula extends javax.swing.JFrame {

    /**
     * Creates new form CargarPelicula
     */
//    private static String url;
//    private static String user;
//    private static String pass;
    public CargarPelicula() {
        initComponents();
//        this.url = "jdbc:mysql://localhost:3306/videoclub";
//        this.user = "root";
//        this.pass = "";
        this.setLocationRelativeTo(null);

        //Creamos los grupos de botones para su correcta eleccion
        buttonGroup1.add(jRadioButton_caset);
        buttonGroup1.add(jRadioButton_dvd);
        buttonGroup2.add(jRadioButton_doble);
        buttonGroup2.add(jRadioButton_simple);
        buttonGroup3.add(jRadioButton_vhs);
        buttonGroup3.add(jRadioButton_beta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_genero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_director = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jRadioButton_dvd = new javax.swing.JRadioButton();
        jRadioButton_simple = new javax.swing.JRadioButton();
        jRadioButton_vhs = new javax.swing.JRadioButton();
        jRadioButton_beta = new javax.swing.JRadioButton();
        jRadioButton_doble = new javax.swing.JRadioButton();
        jRadioButton_caset = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txt_duracion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("PELICULAS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));
        jPanel1.add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 268, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Genero");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));
        jPanel1.add(txt_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 268, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Director");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        jPanel1.add(txt_director, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 268, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Precio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        jPanel1.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 269, -1));

        jRadioButton_dvd.setBackground(new java.awt.Color(153, 153, 255));
        jRadioButton_dvd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_dvd.setText("DVD");
        jPanel1.add(jRadioButton_dvd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jRadioButton_simple.setBackground(new java.awt.Color(153, 153, 255));
        jRadioButton_simple.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_simple.setText("SIMPLE");
        jPanel1.add(jRadioButton_simple, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jRadioButton_vhs.setBackground(new java.awt.Color(153, 153, 255));
        jRadioButton_vhs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_vhs.setText("VHS");
        jPanel1.add(jRadioButton_vhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jRadioButton_beta.setBackground(new java.awt.Color(153, 153, 255));
        jRadioButton_beta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_beta.setText("BETA");
        jPanel1.add(jRadioButton_beta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jRadioButton_doble.setBackground(new java.awt.Color(153, 153, 255));
        jRadioButton_doble.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_doble.setText("DOBLE");
        jPanel1.add(jRadioButton_doble, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jRadioButton_caset.setBackground(new java.awt.Color(153, 153, 255));
        jRadioButton_caset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton_caset.setText("CASET");
        jPanel1.add(jRadioButton_caset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Duracion (colocan en formato HH:MM:SS)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
        jPanel1.add(txt_duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 269, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CARGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 169, 20));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VOLVER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 169, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/graphic-design-3d-abstract-art-hd-wallpaper-wallpaper-preview.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton que carga la pelicula a la base de datos
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Llamamos a pelilcula y le pasamos los valores tomados de los campos para hacer las consultas en el clase
        Pelicula pc = new Pelicula(txt_director.getText(), txt_duracion.getText(), txt_genero.getText(), txt_titulo.getText(), Float.parseFloat(txt_precio.getText()), jRadioButton_beta.isSelected(), jRadioButton_caset.isSelected(), jRadioButton_doble.isSelected(), jRadioButton_dvd.isSelected(), jRadioButton_simple.isSelected(), jRadioButton_vhs.isSelected());

        pc.cargarPelicula();

        //Resetamos todos los valores de la pantalla
        txt_director.setText("");
        txt_duracion.setText("");
        txt_genero.setText("");
        txt_precio.setText("");
        txt_titulo.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    //Boton para cerrar la ventana actual y volver a la pantalla principal
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//        //Me oculta el frame
//       this.setVisible(false);
        //Me cierra el frame
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarPelicula.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarPelicula.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarPelicula.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarPelicula.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarPelicula().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_beta;
    private javax.swing.JRadioButton jRadioButton_caset;
    private javax.swing.JRadioButton jRadioButton_doble;
    private javax.swing.JRadioButton jRadioButton_dvd;
    private javax.swing.JRadioButton jRadioButton_simple;
    private javax.swing.JRadioButton jRadioButton_vhs;
    private javax.swing.JTextField txt_director;
    private javax.swing.JTextField txt_duracion;
    private javax.swing.JTextField txt_genero;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
